#!/usr/bin/env bash

set -o errexit

# set -o nounset


cmd="$@"

# This entrypoint is used to play nicely with the current cookiecutter configuration.
# Since docker-compose relies heavily on environment variables itself for configuration, we'd have to define multip    le
# environment variables just to support cookiecutter out of the box. That makes no sense, so this little entrypoint
# does all this for us.
export REDIS_URL=$REDIS_URL

export CELERY_BROKER_URL="$REDIS_URL"

# the official postgres image uses 'postgres' as default user if not set explictly.
if [ -z "${POSTGRES_USER}" ]; then
       export POSTGRES_USER="$base_postgres_image_default_user"
   fi


export DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB

postgres_ready(){
python << END
import sys
import psycopg
try:
    conn = psycopg.connect(
                            dbname="$POSTGRES_DB",
                            user="$POSTGRES_USER",
                            password="$POSTGRES_PASSWORD",
                            host="$POSTGRES_HOST",
                            port="$POSTGRES_PORT"
                           )

except psycopg.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
      >&2 echo "Postgres is unavailable - sleeping"
      sleep 1
done
>&2 echo "Postgres is up - continuing..."
exec $cmd
